### ISSUE TITLE
libgit2 do not support https

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/vanadis#84]
libgit2/libgit2#3786

Ubuntu 16.04 affect this and couldn't fetch repository over https.

We can solve this in docker image...

**Comment by DronMDF** [comment]
This actual for ubuntu based docker image. Build libgit2 youself?

**Comment by infinity0** [comment]
I have a patch to fix the issue in Debian and Ubuntu which would allow you to avoid these rebuilds. Please review!

**Comment by DronMDF** [comment]
@infinity0:
Thanks...
But this project is freezed.
